
import { SynthSettings } from './types';

export const NOTES = [
  // Octave 1
  { label: 'C3', freq: 130.81 },
  { label: 'C#3', freq: 138.59 },
  { label: 'D3', freq: 146.83 },
  { label: 'D#3', freq: 155.56 },
  { label: 'E3', freq: 164.81 },
  { label: 'F3', freq: 174.61 },
  { label: 'F#3', freq: 185.00 },
  { label: 'G3', freq: 196.00 },
  { label: 'G#3', freq: 207.65 },
  { label: 'A3', freq: 220.00 },
  { label: 'A#3', freq: 233.08 },
  { label: 'B3', freq: 246.94 },
  // Octave 2
  { label: 'C4', freq: 261.63 },
  { label: 'C#4', freq: 277.18 },
  { label: 'D4', freq: 293.66 },
  { label: 'D#4', freq: 311.13 },
  { label: 'E4', freq: 329.63 },
  { label: 'F4', freq: 349.23 },
  { label: 'F#4', freq: 369.99 },
  { label: 'G4', freq: 392.00 },
  { label: 'G#4', freq: 415.30 },
  { label: 'A4', freq: 440.00 },
  { label: 'A#4', freq: 466.16 },
  { label: 'B4', freq: 493.88 },
  { label: 'C5', freq: 523.25 },
];

export const KEY_BINDINGS: Record<string, string> = {
  'z': 'C3', 's': 'C#3', 'x': 'D3', 'd': 'D#3', 'c': 'E3', 'v': 'F3', 'g': 'F#3', 'b': 'G3', 'h': 'G#3', 'n': 'A3', 'j': 'A#3', 'm': 'B3',
  'q': 'C4', '2': 'C#4', 'w': 'D4', '3': 'D#4', 'e': 'E4', 'r': 'F4', '5': 'F#4', 't': 'G4', '6': 'G#4', 'y': 'A4', '7': 'A#4', 'u': 'B4', 'i': 'C5',
};

export const DEFAULT_SETTINGS: SynthSettings = {
  waveform: 'sawtooth',
  envelope: { attack: 0.1, decay: 0.2, sustain: 0.5, release: 0.5 },
  filter: { frequency: 2000, resonance: 1, type: 'lowpass' },
  detune: 0,
  gain: 0.5,
  reverb: 0.3,
  delay: 0.2,
  stereoWidth: 0.8,
  masterTune: 0,
  glide: false,
  glideSpeed: 0.1,
};

export const midiNoteToFrequency = (note: number): number => 440 * Math.pow(2, (note - 69) / 12);
export const NOTE_NAMES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"];
export const getNoteLabel = (midiNote: number): string => {
  const name = NOTE_NAMES[midiNote % 12];
  const octave = Math.floor(midiNote / 12) - 1;
  return `${name}${octave}`;
};

export const TRANSLATIONS = {
  en: {
    appTitle: "Gemini Synth Pro",
    subTitle: "Professional Audio Interface",
    midiStatus: "MIDI Status",
    midiReady: "Ready (No device)",
    midiNotSupported: "Not Supported",
    presetLibrary: "Preset Library",
    savePreset: "Save Preset",
    openLibrary: "Open Library",
    synthesisEngine: "Synthesis Engine",
    adsrPresets: "ADSR Presets",
    oscillator: "Oscillator",
    waveform: "Waveform",
    detune: "Detune",
    masterGain: "Master Vol",
    stereoWidth: "Stereo Width",
    envelope: "Envelope (ADSR)",
    attack: "Attack",
    decay: "Decay",
    sustain: "Sustain",
    release: "Release",
    filter: "Filter",
    cutoff: "Cutoff",
    resonance: "Resonance",
    effects: "Effects",
    delayMix: "Delay Mix",
    reverbMix: "Reverb Mix",
    frequencySpectrum: "Frequency Spectrum",
    engineLoad: "Engine Load",
    performanceTip: "Performance Tip",
    performanceTipDesc: "Use Z-M and Q-I keys or connect a MIDI controller. Press REC to capture loops!",
    stereoOutput: "Stereo Output",
    latencyLow: "Latency: Low",
    midiActive: "MIDI: Active",
    midiOffline: "MIDI: Offline",
    presetNameLabel: "Preset Name",
    save: "SAVE",
    cancel: "CANCEL",
    savedPresets: "Saved Presets",
    emptyLibrary: "Your library is empty. Save a sound!",
    localStoreNotice: "All sounds are stored locally.",
    sequencer: "Sequencer & Loops",
    rec: "REC",
    stop: "STOP",
    globalStop: "GLOBAL STOP",
    noLoops: "No loops recorded yet. Hit REC!",
    play: "Play",
    restart: "Restart",
    fastAttack: "Fast Attack",
    slowAttack: "Slow Attack",
    sustained: "Sustained",
    quickRelease: "Quick Release"
  },
  zh: {
    appTitle: "Gemini 合成器专业版",
    subTitle: "专业级音频接口",
    midiStatus: "MIDI 状态",
    midiReady: "就绪 (未连接设备)",
    midiNotSupported: "不支持",
    presetLibrary: "预设库",
    savePreset: "保存预设",
    openLibrary: "打开库",
    synthesisEngine: "合成引擎",
    adsrPresets: "包络预设",
    oscillator: "振荡器",
    waveform: "波形",
    detune: "细微调音",
    masterGain: "主音量",
    stereoWidth: "立体声宽度",
    envelope: "包络 (ADSR)",
    attack: "起音 (Attack)",
    decay: "衰减 (Decay)",
    sustain: "延持 (Sustain)",
    release: "释音 (Release)",
    filter: "滤波器",
    cutoff: "截止频率",
    resonance: "共鸣",
    effects: "效果器",
    delayMix: "延迟混响",
    reverbMix: "混响强度",
    frequencySpectrum: "频谱可视化",
    engineLoad: "引擎负载",
    performanceTip: "演奏技巧",
    performanceTipDesc: "使用 Z-M 和 Q-I 键或连接 MIDI 控制器。点击 REC 录制循环！",
    stereoOutput: "立体声输出",
    latencyLow: "延迟: 低",
    midiActive: "MIDI: 已激活",
    midiOffline: "MIDI: 离线",
    presetNameLabel: "预设名称",
    save: "保存",
    cancel: "取消",
    savedPresets: "已保存的预设",
    emptyLibrary: "库中没有预设。保存一个声音吧！",
    localStoreNotice: "所有声音都存储在本地浏览器中。",
    sequencer: "序列器与循环",
    rec: "录制",
    stop: "停止",
    globalStop: "全局停止",
    noLoops: "尚未录制循环。点击 REC 开始！",
    play: "播放",
    restart: "重新开始",
    fastAttack: "快速起音",
    slowAttack: "慢速起音",
    sustained: "持续音",
    quickRelease: "快速释放"
  }
};